# [Indexing] Aufgabe Indexing

In [2]:
import pandas as pd

In [3]:
kunden = pd.read_excel("Kunden.xlsx")

In [4]:
kunden

,Kunden-ID,Kunde,Adress-ID,Land,Postleitzahl,Stadt,Straße
0,1,Sauter AG,3,Deutschland,10115,Berlin,Hauptstraße 34
1,2,Preuß GmbH & Co. KG,10,Deutschland,28195,Bremen,Beethovenplatz 65
2,3,Kunz & Partner cz.,16,Tschechien,21035,Hamburg,Bismarckring 2
3,4,Eder Edelmetalle GmbH,4,Deutschland,79098,Freiburg,Rathausgasse 82
4,5,Wild-Schubert OHG,12,Deutschland,76135,Karlsruhe,Lange Gasse 62
5,6,FSA-L SAS,26,Deutschland,75000,Paris,Rue Abel 102
6,7,"Crawfort, Inc.",15,Südafrika,10012,New York,Main Street 12
7,8,"Hegman, Sas.",17,Italien,7097,New Jersey,Ms Jay 22 Avebury Street
8,9,"Collins, Ltd.",25,Litauen,90049,Los Angeles,Monroe Street
9,10,Fischer Kft.,20,Ungarn,63327,Hennigsdorf,Hans-Hermann-Diehl-Straße 5/9
10,11,Martens GmbH,5,Deutschland,15390,Greifswald,Mandy-Neumann-Straße 99
11,12,Stark Kft.,27,Ungarn,53299,Siegen,Diana-Schwarz-Allee 8a
12,13,Krug GmbH,13,Deutschland,16042,Moers,Rosemarie-Kunz-Allee 4/3
13,14,"Kreiger, Inc.",2,Deutschland,30845,O'Reillyfort,4706 Ebony Bridge
14,15,MTE Ltd.,29,Indonesien,2089,South Rob,8698 William Coves Apt. 953
15,16,Turnow S.L.,30,Spanien,38331,Maryhaven,7286 Sebastian Divide
16,17,Weichert S.L.,18,Spanien,11178,San Nazzareno del friuli,Via Alessio 271
17,18,Hutter Kft.,22,Ungarn,5231,Armas de Arriba,"Calle Elena, 75, Bajo 8"
18,19,Bohn S.A.,19,Neuseeland,3592,Sigmundston,08 Ulises Street
19,20,Protz Lft.,24,Indonesien,3542,Letenye,Balázs üdülőpart 810. 26. emelet
20,21,Kuttner Inc.,8,USA,6700,Budapest,Oláh játszótér 741. 64. emelet
21,22,Velikov GmbH & CO KG,11,Deutschland,9466,Somogy,Léna átjáró 164.
22,23,Butherus Inc.,7,USA,7751,Debrecen,Veres átjáró 5. 39. ajtó
23,24,Jungmann Kft.,1,Deutschland,22319,Ternate,Ds. Bacang No. 923
24,25,Herfs Inc.,14,USA,82543,Conroyfurt,74027 Harvey Path Suite 807
25,26,Stollenwerk Inc.,9,USA,30486,Ludwigsburg,Alexander-Michels-Platz 4a
26,27,Wilhelmi S.A.S.,6,Frankreich,1407,Debrecen,Fehér dűlősor 958.\t
27,28,Selle Kft.,23,Ungarn,86472,New Gregoriabury,4528 Jerde View
28,29,Donath Corp.,28,USA,58974,Bogor,Psr. Moch. Yamin No. 842
29,30,Henseler GmbH,21,Ungarn,24258,San Serrato,"Passeig Prado, 556, 5º"

## Aufgabe 1: "iloc"-Filterung

### 1.1) Erste Zeile (Index = 0)

In [6]:
kundenNeu = kunden.iloc[0]
kundenNeu

Kunden-ID                    1
Kunde                Sauter AG
Adress-ID                    3
Land               Deutschland
Postleitzahl             10115
Stadt                   Berlin
Straße          Hauptstraße 34
Name: 0, dtype: object

### 1.2) Zweite Zeile (Index = 1)

In [7]:
kundenNeu = kunden.iloc[1]
kundenNeu

Kunden-ID                         2
Kunde           Preuß GmbH & Co. KG
Adress-ID                        10
Land                    Deutschland
Postleitzahl                  28195
Stadt                        Bremen
Straße            Beethovenplatz 65
Name: 1, dtype: object

### 1.3) Letzte Zeile

In [8]:
kundenNeu = kunden.iloc[len(kunden)- 1]
kundenNeu

Kunden-ID                           30
Kunde                    Henseler GmbH
Adress-ID                           21
Land                            Ungarn
Postleitzahl                     24258
Stadt                      San Serrato
Straße          Passeig Prado, 556, 5º
Name: 29, dtype: object

### 1.4) Vierte Spalte und alle Zeilen

In [10]:
kundenNeu = kunden.iloc[:, 3]
kundenNeu

0     10115
1     28195
2     21035
3     79098
4     76135
5     75000
6     10012
7      7097
8     90049
9     63327
10    15390
11    53299
12    16042
13    30845
14     2089
15    38331
16    11178
17     5231
18     3592
19     3542
20     6700
21     9466
22     7751
23    22319
24    82543
25    30486
26     1407
27    86472
28    58974
29    24258
Name: Postleitzahl, dtype: int64

### 1.5) Letzte Spalte

In [14]:
kundenNeu = kunden.iloc[:, len(kunden.columns)-1]
kundenNeu

0                       Hauptstraße 34
1                    Beethovenplatz 65
2                       Bismarckring 2
3                      Rathausgasse 82
4                       Lange Gasse 62
5                         Rue Abel 102
6                       Main Street 12
7             Ms Jay 22 Avebury Street
8                        Monroe Street
9        Hans-Hermann-Diehl-Straße 5/9
10             Mandy-Neumann-Straße 99
11              Diana-Schwarz-Allee 8a
12            Rosemarie-Kunz-Allee 4/3
13                   4706 Ebony Bridge
14         8698 William Coves Apt. 953
15               7286 Sebastian Divide
16                     Via Alessio 271
17             Calle Elena, 75, Bajo 8
18                    08 Ulises Street
19    Balázs üdülőpart 810. 26. emelet
20      Oláh játszótér 741. 64. emelet
21                    Léna átjáró 164.
22            Veres átjáró 5. 39. ajtó
23                  Ds. Bacang No. 923
24         74027 Harvey Path Suite 807
25          Alexander-Michels-Platz 4a
26                Fehér dűlősor 958.\t
27                     4528 Jerde View
28            Psr. Moch. Yamin No. 842
29              Passeig Prado, 556, 5º
Name: Straße, dtype: object

### 1.6) Nur die Spalten "Land", "Postleitzahl" und "Stadt"

In [15]:
kundenNeu = kunden.iloc[:, [3, 4, 5]]
kundenNeu

           Land  Postleitzahl                     Stadt
0   Deutschland         10115                    Berlin
1   Deutschland         28195                    Bremen
2    Tschechien         21035                   Hamburg
3   Deutschland         79098                  Freiburg
4   Deutschland         76135                 Karlsruhe
5   Deutschland         75000                     Paris
6     Südafrika         10012                 New York
7       Italien          7097                New Jersey
8       Litauen         90049               Los Angeles
9        Ungarn         63327               Hennigsdorf
10  Deutschland         15390                Greifswald
11       Ungarn         53299                    Siegen
12  Deutschland         16042                     Moers
13  Deutschland         30845              O'Reillyfort
14   Indonesien          2089                 South Rob
15      Spanien         38331                 Maryhaven
16      Spanien         11178  San Nazzareno del friuli
17       Ungarn          5231           Armas de Arriba
18   Neuseeland          3592               Sigmundston
19   Indonesien          3542                   Letenye
20          USA          6700                  Budapest
21  Deutschland          9466                    Somogy
22          USA          7751                  Debrecen
23  Deutschland         22319                   Ternate
24          USA         82543                Conroyfurt
25          USA         30486               Ludwigsburg
26   Frankreich          1407                  Debrecen
27       Ungarn         86472          New Gregoriabury
28          USA         58974                     Bogor
29       Ungarn         24258               San Serrato

### 1.7) Nur die Spalten "Kunde", "Land" und "Stadt"

In [ ]:
kunden.iloc[:, [1, 3, 5]]

## Aufgabe 2: "loc"-Filterung

### 2.1) Alle Einträge

In [16]:
kunden.loc[:,:]

,Kunden-ID,Kunde,Adress-ID,Land,Postleitzahl,Stadt,Straße
0,1,Sauter AG,3,Deutschland,10115,Berlin,Hauptstraße 34
1,2,Preuß GmbH & Co. KG,10,Deutschland,28195,Bremen,Beethovenplatz 65
2,3,Kunz & Partner cz.,16,Tschechien,21035,Hamburg,Bismarckring 2
3,4,Eder Edelmetalle GmbH,4,Deutschland,79098,Freiburg,Rathausgasse 82
4,5,Wild-Schubert OHG,12,Deutschland,76135,Karlsruhe,Lange Gasse 62
5,6,FSA-L SAS,26,Deutschland,75000,Paris,Rue Abel 102
6,7,"Crawfort, Inc.",15,Südafrika,10012,New York,Main Street 12
7,8,"Hegman, Sas.",17,Italien,7097,New Jersey,Ms Jay 22 Avebury Street
8,9,"Collins, Ltd.",25,Litauen,90049,Los Angeles,Monroe Street
9,10,Fischer Kft.,20,Ungarn,63327,Hennigsdorf,Hans-Hermann-Diehl-Straße 5/9
10,11,Martens GmbH,5,Deutschland,15390,Greifswald,Mandy-Neumann-Straße 99
11,12,Stark Kft.,27,Ungarn,53299,Siegen,Diana-Schwarz-Allee 8a
12,13,Krug GmbH,13,Deutschland,16042,Moers,Rosemarie-Kunz-Allee 4/3
13,14,"Kreiger, Inc.",2,Deutschland,30845,O'Reillyfort,4706 Ebony Bridge
14,15,MTE Ltd.,29,Indonesien,2089,South Rob,8698 William Coves Apt. 953
15,16,Turnow S.L.,30,Spanien,38331,Maryhaven,7286 Sebastian Divide
16,17,Weichert S.L.,18,Spanien,11178,San Nazzareno del friuli,Via Alessio 271
17,18,Hutter Kft.,22,Ungarn,5231,Armas de Arriba,"Calle Elena, 75, Bajo 8"
18,19,Bohn S.A.,19,Neuseeland,3592,Sigmundston,08 Ulises Street
19,20,Protz Lft.,24,Indonesien,3542,Letenye,Balázs üdülőpart 810. 26. emelet
20,21,Kuttner Inc.,8,USA,6700,Budapest,Oláh játszótér 741. 64. emelet
21,22,Velikov GmbH & CO KG,11,Deutschland,9466,Somogy,Léna átjáró 164.
22,23,Butherus Inc.,7,USA,7751,Debrecen,Veres átjáró 5. 39. ajtó
23,24,Jungmann Kft.,1,Deutschland,22319,Ternate,Ds. Bacang No. 923
24,25,Herfs Inc.,14,USA,82543,Conroyfurt,74027 Harvey Path Suite 807
25,26,Stollenwerk Inc.,9,USA,30486,Ludwigsburg,Alexander-Michels-Platz 4a
26,27,Wilhelmi S.A.S.,6,Frankreich,1407,Debrecen,Fehér dűlősor 958.\t
27,28,Selle Kft.,23,Ungarn,86472,New Gregoriabury,4528 Jerde View
28,29,Donath Corp.,28,USA,58974,Bogor,Psr. Moch. Yamin No. 842
29,30,Henseler GmbH,21,Ungarn,24258,San Serrato,"Passeig Prado, 556, 5º"

### 2.2) Nur die erste Zeile (Index=0)

In [18]:
kunden.loc[0,:]

Kunden-ID                         2
Kunde           Preuß GmbH & Co. KG
Adress-ID                        10
Land                    Deutschland
Postleitzahl                  28195
Stadt                        Bremen
Straße            Beethovenplatz 65
Name: 1, dtype: object

### 2.3) Nur die ersten 7 Zeilen (Index=0-6)

In [19]:
kunden.loc[0:6,:]

,Kunden-ID,Kunde,Adress-ID,Land,Postleitzahl,Stadt,Straße
0,1,Sauter AG,3,Deutschland,10115,Berlin,Hauptstraße 34
1,2,Preuß GmbH & Co. KG,10,Deutschland,28195,Bremen,Beethovenplatz 65
2,3,Kunz & Partner cz.,16,Tschechien,21035,Hamburg,Bismarckring 2
3,4,Eder Edelmetalle GmbH,4,Deutschland,79098,Freiburg,Rathausgasse 82
4,5,Wild-Schubert OHG,12,Deutschland,76135,Karlsruhe,Lange Gasse 62
5,6,FSA-L SAS,26,Deutschland,75000,Paris,Rue Abel 102
6,7,"Crawfort, Inc.",15,Südafrika,10012,New York,Main Street 12

### 2.4) Kunde als Index setzen

In [26]:
kunden = kunden.set_index("Kunde")

### 2.5) Nur Zeilen mit Kunden "FSA-L SAS", "Hegman, Sas." und "Herfs Inc."

In [27]:
kunden.loc[["FSA-L SAS", "Hegman, Sas.", "Herfs Inc."], :]

,Kunden-ID,Adress-ID,Land,Postleitzahl,Stadt,Straße
Kunde,,,,,,
FSA-L SAS,6,26,Deutschland,75000,Paris,Rue Abel 102
"Hegman, Sas.",8,17,Italien,7097,New Jersey,Ms Jay 22 Avebury Street
Herfs Inc.,25,14,USA,82543,Conroyfurt,74027 Harvey Path Suite 807

### 2.6) Nur Spalten "Land", "Stadt" und "Straße" für Kunden "Jungmann Kft.	"

In [29]:
kunden.loc["Jungmann Kft.", ["Land", "Stadt","Straße"]]

Land             Deutschland
Stadt                Ternate
Straße    Ds. Bacang No. 923
Name: Jungmann Kft., dtype: object